# automatically generated by the FlatBuffers compiler, do not modify

# namespace: feed

class Body(object):
    NONE = 0
    FeedRequest = 1
    FeedRequestReject = 2
    MDSnapshotL2 = 3
    PublicTrade = 4
    SessionStatus = 5

