# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class AssetType(object):
    None_ = 0
    Cmdty = 1
    Corp = 2
    Ccy = 3
    Eqty = 4
    Govt = 5
    Index = 6
    Crypto = 7

