# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class Body(object):
    NONE = 0
    Asset = 1
    Instr = 2
    Venue = 3
    Market = 4
    Order = 5
    Exec = 6
    Posn = 7
    MarketData = 8
    MarketDataRequest = 9
    MarketDataRequestReject = 10
    MarketInfo = 11
    RevalRates = 12
    PublicTrade = 13
    FullAmount = 14
    Quote = 15
    DealerQuote = 16

