# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class Body(object):
    NONE = 0
    Asset = 1
    Instr = 2
    Venue = 3
    Market = 4
    Order = 5
    Exec = 6
    Posn = 7
    MarketData = 8
    MarketInfo = 9
    RevalRates = 10
    PublicTrade = 11
    FullAmount = 12
    Quote = 13
    DealerQuote = 14
    MarketDataRequest = 15
    MarketDataRequestReject = 16

