# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class ExecType(object):
    None_ = 0
    New = 1
    Revised = 2
    Cancelled = 3
    Trade = 4
    Rejected = 5
    Stopped = 6
    Expired = 7
    PendingNew = 8
    PendingRevise = 9
    PendingCancel = 10
    PendingSuspend = 11
    Suspended = 12
    PendingResume = 13

