# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class MarketDataRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMarketDataRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MarketDataRequest()
        x.Init(buf, n + offset)
        return x

    # MarketDataRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MarketDataRequest
    def SubReqType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # MarketDataRequest
    def Markets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # MarketDataRequest
    def MarketsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def MarketDataRequestStart(builder): builder.StartObject(2)
def MarketDataRequestAddSubReqType(builder, subReqType): builder.PrependInt16Slot(0, subReqType, 0)
def MarketDataRequestAddMarkets(builder, markets): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(markets), 0)
def MarketDataRequestStartMarketsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def MarketDataRequestEnd(builder): return builder.EndObject()
