# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class MarketDataFlag(object):
    Level3 = 1
    Bucketed = 2
    NonSweepable = 4
    Tradeable = 8
    FullAmountLadder = 16

