# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class MDEntry(object):
    __slots__ = ['_tab']

    # MDEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MDEntry
    def Level(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MDEntry
    def VenueId(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # MDEntry
    def Qty(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # MDEntry
    def Price(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateMDEntry(builder, level, venueId, qty, price):
    builder.Prep(8, 24)
    builder.PrependFloat64(price)
    builder.PrependFloat64(qty)
    builder.PrependInt32(venueId)
    builder.PrependInt32(level)
    return builder.Offset()
