# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class MDLevel(object):
    __slots__ = ['_tab']

    # MDLevel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MDLevel
    def Qty(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MDLevel
    def Price(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # MDLevel
    def AvgPrice(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # MDLevel
    def Count(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateMDLevel(builder, qty, price, avgPrice, count):
    builder.Prep(8, 32)
    builder.Pad(4)
    builder.PrependInt32(count)
    builder.PrependFloat64(avgPrice)
    builder.PrependFloat64(price)
    builder.PrependFloat64(qty)
    return builder.Offset()
