# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class MDRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMDRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MDRequest()
        x.Init(buf, n + offset)
        return x

    # MDRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MDRequest
    def SubReqType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MDRequest
    def Markets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # MDRequest
    def MarketsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def MDRequestStart(builder): builder.StartObject(2)
def MDRequestAddSubReqType(builder, subReqType): builder.PrependInt32Slot(0, subReqType, 0)
def MDRequestAddMarkets(builder, markets): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(markets), 0)
def MDRequestStartMarketsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def MDRequestEnd(builder): return builder.EndObject()
